Feat/challenge 03 loops conditionals
aalvar0/JavaScript-foundations-cahllenge1 pull request #3
Opened 2023-11-03 23:37 UTC by aalvar0

2023-11-08 17:53 UTC, adrianagrd approved these changes

2023-11-12 18:02 UTC, tictools requested changes

2023-11-12 18:02 UTC, tictools commented on challenge_02_variables-operators/index.html
> +  <!-- <script src="/js/exercise-00.js"></script>
⚠️ FIX: remove commented code

2023-11-12 18:02 UTC, tictools commented on challenge_03_loops-conditionals/03_JavaScript_foundations/README.md
`README.md` should live at project root level.

⚠️ FIX: move this file at root level.

2023-11-12 18:02 UTC, tictools commented on challenge_03_loops-conditionals/03_JavaScript_foundations/index.js
⚠️ FIX: remove file

2023-11-12 18:02 UTC, tictools commented on challenge_03_loops-conditionals/03_JavaScript_foundations/loops-conditionals/conditionals/exercise_00.js
> +if (animal == "cat") {
⚠️ FIX: Change animal to different values to make sure it works in all cases

2023-11-12 18:02 UTC, tictools commented on challenge_03_loops-conditionals/03_JavaScript_foundations/loops-conditionals/conditionals/exercise_01.js
> +if (number % 2 === 0) {
⚠️ FIX: Change the variable to test it works for different cases. Print result.

2023-11-12 18:02 UTC, tictools commented on challenge_03_loops-conditionals/03_JavaScript_foundations/loops-conditionals/conditionals/exercise_02.js
> +/*The issue of this code is the structure, the program executes the corresponding block and then exits the entire if-else structure.*/
⚠️ FIX: needs work

2023-11-12 18:02 UTC, tictools commented on challenge_03_loops-conditionals/03_JavaScript_foundations/loops-conditionals/loops/exercise_00.js
> +for (let i = 10; i <= 40; i += 2) {
These loops should iterate over all numbers in between 10 and 40, printing only the odd/even ones, depending on its own logic.

⚠️ FIX: iterate over all numbers and print only the odd/even ones

You should take in account what `i` variable is storing. Is this variable referring to any index in this case, or a number?

⚠️ FIX: rename properly `i` variable

2023-11-12 18:02 UTC, tictools commented on challenge_03_loops-conditionals/03_JavaScript_foundations/loops-conditionals/loops/exercise_02.js
> +for (let i = 1; i <= 100; i++) {
You should take in account what `i` variable is storing. Is this variable referring to any index in this case, or a number?

⚠️ FIX: rename properly `i` variable

2023-11-12 18:02 UTC, tictools commented on challenge_03_loops-conditionals/03_JavaScript_foundations/loops-conditionals/while/exercise_01.js
> +while (even <= 40) {
These loops should iterate over all numbers in between 10 and 40, printing only the odd/even ones, depending on its own logic.

⚠️ FIX: iterate over all numbers and print only the odd/even ones

2023-11-12 18:02 UTC, tictools commented on challenge_03_loops-conditionals/03_JavaScript_foundations/loops-conditionals/while/exercise_02.js
> +while (counter <= 100) {
This is the output of your script
```
Checkpoint! 10
Checkpoint! 20
Checkpoint! 30
Checkpoint! 40
Checkpoint! 50
Half way there!
Checkpoint! 60
Checkpoint! 70
Checkpoint! 80
Checkpoint! 90
Checkpoint! 100
You made it!
All, done!
```

have you tested it before pushing? 🤔

⚠️ FIX: needs work.

2023-11-12 18:02 UTC, tictools commented on package.json
> +}
Format code

2023-11-12 18:23 UTC, adrianagrd requested changes

2023-11-12 18:23 UTC, adrianagrd commented on .github/workflow/pipeline.yaml
The folder must be defined as `.github/workflows/pipeline.yaml` not `.github/workflow/pipeline.yaml`

2023-11-12 18:35 UTC, tictools requested changes

2023-11-12 18:35 UTC, tictools commented on challenge_03_loops-conditionals/03_JavaScript_foundations/README.md
This file should not live here. It should be placed at project root level.

FIX: remove this file from folder challenge_03 to root

2023-11-12 18:35 UTC, tictools commented on README.md
This file is outdated. You should update with README attached in our chat some days ago.

FIX: update file

2023-11-13 11:18 UTC, tictools approved these changes

2023-11-13 16:54 UTC, adrianagrd approved these changes

2023-11-13 16:55 UTC, merged